groups:
  - name: main
    jobs:
    - my-first-job

jobs:
  - name: my-first-job
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
              tag: latest

          run:
            path: /bin/bash
            args:
              - -exc
              - |
                echo "hello world"
