groups:
  - name: main
    jobs:
    - my-first-job

  - name: bbl-env
    jobs:
      - build-bbl-image


resources:
  - name: lab-repo
    type: git
    source:
      branch: master
      uri: https://github.com/cf-platform-eng/concourse-lab.git

  - name: bbl-image
    type: docker-image
    source:
      repository: ((docker_repo))
      username: ((docker_hub.username))
      password: ((docker_hub.password))
      tag: ((bbl_version))


jobs:
  - name: my-first-job
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
              tag: latest

          run:
            path: /bin/bash
            args:
              - -exc
              - |
                echo "hello world"

  - name: build-bbl-image
    plan:
      - get: lab-repo
        trigger: true
        # Runs the get, now container has /lab-repo
        # /lab-repo contains the data from git@github.com:cf-platform-eng/lab-repo.git
        # the contents of /lab-repo are from the latest version found during the `check` stage
      - put: bbl-image
        params:
          build: lab-repo
          dockerfile: lab-repo/Dockerfile.bbl # only need this param because we used a name other than `Dockerfile`
          # equivalent to:
          #  docker build lab-repo -f lab-repo/Dockerfile.bbl -t cfplatformeng/concourse-lab-bbl-image
          #  docker push cfplatformeng/concourse-lab-bbl-image


